viaa:
  logging:
    level: DEBUG
app:
  rabbitmq:
    host: !ENV ${RABBITMQ_HOST}
    port: 5672
    username: !ENV ${RABBITMQ_USERNAME}
    password: !ENV ${RABBITMQ_PASSWORD}
    queue: !ENV ${RABBITMQ_QUEUE}
    prefetch_count: !ENV ${RABBITMQ_PREFETCH_COUNT}
  destination:
    free_space_percentage: !ENV ${SSH_FREE_SPACE_PERCENTAGE}
    file_system: !ENV ${SSH_FILE_SYSTEM}
  vault:
    url: !ENV ${VAULT_URL}
    token: !ENV ${VAULT_TOKEN}
  pulsar:
    host: !ENV ${PULSAR_HOST}
    port: 6650
