apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "exec"
  name: "s3-transfer-service"
  labels:
    app: "s3-transfer-service"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "s3-transfer-service-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-transfer-service"
        app.kubernetes.io/component: "s3-transfer-service-${env}"
        app.kubernetes.io/instance: "s3-transfer-service-${env}"
        app.kubernetes.io/name: "s3-transfer-service"
        app.kubernetes.io/part-of: "s3-transfer-service"
        app.openshift.io/runtime: "s3-transfer-service"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "s3-transfer-service-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
        image.openshift.io/triggers: >-
          [{'from':{'kind':'ImageStreamTag','name':'s3-transfer-service:${env}','namespace':'s3-components'},'fieldPath':'spec.template.spec.containers[?(@.name==\'s3-transfer-service-${env}\')].image','pause':'false'}]
      name: "s3-transfer-service-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-transfer-service"
        app.kubernetes.io/component: "s3-transfer-service-${env}"
        app.kubernetes.io/instance: "s3-transfer-service-${env}"
        app.kubernetes.io/name: "s3-transfer-service"
        app.kubernetes.io/part-of: "s3-transfer-service"
        app.openshift.io/runtime: "s3-transfer-service"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "s3-transfer-service-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "s3-transfer-service-${env}"
            deploymentconfig: "s3-transfer-service-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "s3-transfer-service-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "s3-transfer-service-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/s3-components/s3-transfer-service:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "s3-transfer-service-${env}"
      namespace: "s3-components"
      labels:
        app: "s3-transfer-service"
        app.kubernetes.io/component: "s3-transfer-service-${env}"
        app.kubernetes.io/instance: "s3-transfer-service-${env}"
        app.kubernetes.io/name: "s3-transfer-service"
        app.kubernetes.io/part-of: "s3-transfer-service"
        app.openshift.io/runtime: "s3-transfer-service"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      RABBITMQ_HOST: some_value
      RABBITMQ_USERNAME: some_value
      RABBITMQ_PASSWORD: some_value
      RABBITMQ_QUEUE: some_value
      RABBITMQ_PREFETCH_COUNT: some_value
      CASTOR_SWARMURL: some_value
      CASTOR_SWARMDOMAIN: some_value
      SSH_HOST: some_value
      SSH_USER: some_value
      SSH_PASSWORD: some_value
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"